repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: check-yaml

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.11
    hooks:
      - id: ruff
        args: ["--fix"]

  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.18.1
    hooks:
      - id: markdownlint-cli2

  # Local hook to run tests with coverage before push
  - repo: local
    hooks:
      - id: pytest-cov
        name: pytest with coverage (min 60%)
        entry: pytest -q --cov=trade_clone_engine --cov-report=term-missing --cov-report=xml --cov-fail-under=60
        language: system
        pass_filenames: false
        stages: [pre-push]
