name: Bug report
description: Report a problem
labels: [bug]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the bug and expected behavior.
      placeholder: Clear steps to reproduce...
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant logs
      render: shell
  - type: input
    id: version
    attributes:
      label: Version / git SHA
  - type: dropdown
    id: area
    attributes:
      label: Area
      options:
        - watcher
        - executor
        - api
        - discovery
        - docs
