blank_issues_enabled: false
contact_links:
  - name: Security issue
    url: https://github.com/your-org/your-repo/security/policy
    about: Please report security vulnerabilities privately via the Security Policy.
