name: Feature request
description: Suggest an idea
labels: [enhancement]
body:
  - type: textarea
    id: proposal
    attributes:
      label: Proposal
      description: What would you like to add or change?
    validations:
      required: true
  - type: textarea
    id: rationale
    attributes:
      label: Rationale
      description: Why is this valuable? Keep it educational; no financial advice.
  - type: textarea
    id: additional
    attributes:
      label: Additional context
