name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install system deps
        run: sudo apt-get update && sudo apt-get install -y libpq-dev
      - name: Install package
        run: |
          python -m pip install --upgrade pip
          pip install -e .
      - name: Ruff lint
        run: |
          pip install ruff
          ruff --version
          # Check formatting and lint with GitHub-friendly output
          ruff format --check .
          ruff check . --output-format=github
      - name: Run tests with coverage
        run: |
          pytest -q --cov=trade_clone_engine --cov-report=term-missing --cov-report=xml
      - name: Upload coverage to artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: coverage.xml
          flags: unittests
          fail_ci_if_error: true
          verbose: true

  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Markdownlint
        uses: DavidAnson/markdownlint-cli2-action@v18
        with:
          globs: |
            **/*.md

  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1
